### ISSUE TITLE
Use spacing as per WordPress coding standards

### ISSUE THREAD

**Issue by davemac** [baerkins/acf_snippets#4]
With all snippets, current output does not use spacing (for example):

`the_field('field_name');`

It would be great if the snippets followed WP coding standards and used spacing:

`the_field( 'field_name' );`

[https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage](Core Handbook Reference)

**Comment by baerkins** [comment]
Closed in ed1ff6bc2f04cd61e49b815390f56ed194398f8d, if you catch anything that slipped through, let me know!

Thanks for the suggestion - Cheers!
